# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'


      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Run Maven build and tests
      - name: Build and Test
        run: mvn clean install

      # Passo 5: Gerar o relatório JaCoCo
      - name: Run JaCoCo code coverage report
        run: mvn jacoco:report

      # Passo 6: Publicar o relatório JaCoCo como um artefato
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco-aggregate/index.html

      # Passo 7: (Opcional) Publicar o relatório como um GitHub Pages, se você quiser visualizar diretamente
      - name: Deploy JaCoCo Report to GitHub Pages
        if: success()
        run: |
          mkdir -p gh-pages
          cp target/site/jacoco-aggregate/index.html gh-pages/
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add gh-pages
          git commit -m "Deploy JaCoCo report"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages:gh-pages
          
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
